 service: lambda-probot-express

 provider:
   name: aws
   runtime: nodejs14.x
   region: us-east-1

 functions:
   router:
     handler: handler.webhooks

     environment:
       WEBHOOK_SECRET: ${ssm:/webhook_secret}
       APP_ID: ${ssm:/app_id}
       PRIVATE_KEY: ${ssm:/privateKey}
       LOG_FORMAT: json 

     events:
       - http:
          path: /api/github/webhooks
          method: post