 service: lambda-probot-express

 provider:
   name: aws
   runtime: nodejs12.x
   region: us-east-1

 functions:
   router:
     handler: handler.webhooks

     environment:
       # replace values with one\'s associated to your app
       WEBHOOK_SECRET: my-secret
       APP_ID: ${ssm:/app_id}
       PRIVATE_KEY: ${ssm:/privateKey}
       LOG_FORMAT: json 

     events:
       - http:
          path: /api/github/webhooks
          method: post
